version: '3.8'

services:

  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    restart: always
    volumes:
      - .:/code
      - ./staticfiles/:/code/staticfiles/
    depends_on:
      - db
    networks:
      - default

  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles/:/static
    ports:
      - 80:80
    depends_on:
      - web
    networks:
      - default

volumes:
  postgres_data: